version: "3.1"
services:

  php:
    build: docker/php
    container_name: ${PROJECT_NAME}-php
    working_dir: /application
    volumes:
      - ./criptobot:/application
      - ./docker/php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    ports:
      - "9262:9000"

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-nginx
    working_dir: /application
    depends_on:
      - php
    volumes:
        - .:/application
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - .:/mysql/data
    ports:
      - "8262:80"
    
  mysql:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}-mysql
    working_dir: /mysql/data
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3262:3306"

  mongo:
    image: mongo
    container_name: ${PROJECT_NAME}-mongo
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./docker/mongo/mongo-volume:/data/db
    ports:
      - "27017-27019:27017-27019"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8261:80"

networks:
  default:
    external:
      name: cripto
